# Семинар 1: знакомство с NumPy


In [ ]:
print('hi')

hi


## Немного про Jupyter notebook

Полная документация: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

---
В Jupyter Notebook есть два режима работы: режим _команд_ и режим _редактирования_

_Командный_ режим нужен для того, чтобы взаимодействовать и управлять ячейками (добавлять, удалять, запускать, копировать, ...)

В режиме _редактирования_ вы меняете содержимое ячейки.

Ячейки бывают двух основных типов, _код_ и _разметка_

### Полезные команды

(находясь в командном режиме)

- `a` - добавить пустую ячейку сверху

- `b` - добавить пустую ячейку снизу
- `c` - скопировать текущую ячейку
- `v` - вставить скопированную ячейку
- `d` - удалить текущую ячейку
- `x` - вырезать (удалить и скопировать) текущую ячейку
- `m` - изменить тип выбранной ячейки на "разметка"
- `y` - изменить тип выбранной ячейки на "код"
- `z` - отменить последнее действие


- `Enter` - начать редактировать выбранную ячейку

(будучи в режим редактирования ячейки)
- `esc` - вернуться в командный режим

(будучи в любом режиме)

- `Ctrl + Enter` - запустить выбранную ячейку
- `Shift + Enter` - запустить выбранную ячейку и выбрать следующую

In [ ]:
2 + 2

5

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [3]:
import numpy as np

In [15]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [16]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [18]:
vec.dtype

dtype('int64')

In [19]:
type(vec)

numpy.ndarray

Размер массива:

In [20]:
vec.shape

(3, 2)

Число осей:

In [21]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [22]:
np.sum(vec)

np.int64(21)

In [23]:
np.sum(vec, axis=0)

array([ 9, 12])

In [24]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [25]:
vec.sum()

np.int64(21)

Транспонируем массив:

In [26]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [27]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [28]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [29]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

Индексирование:

In [32]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
vec[:, 1]

array([2, 4, 6])

In [34]:
vec[2, :]

array([5, 6])

In [35]:
vec[1:2, 0]

array([3])

In [36]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

И, наконец - арифметические операции!

In [37]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [38]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [39]:
vec**2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [40]:
vec + vec**2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [41]:
vec * vec**2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [42]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [44]:
vec.dot((vec**2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [45]:
vec @ (vec**2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [46]:
vec @ (vec.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [48]:
arr = np.arange(5, 10)*2
print(arr)

[10 12 14 16 18]


Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [47]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [50]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Булевы массивы:

In [51]:
is_even = vec % 2 == 0
print(is_even)

[[False  True]
 [False  True]
 [False  True]]


In [53]:
np.sum(is_even)

np.int64(3)

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [54]:
vec[vec % 2 == 0]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [55]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [56]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [ ]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [57]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Генерация случайных чисел:

In [ ]:
np.random.seed(623)
np.random.rand(2, 3)

array([[0.70373071, 0.8009102 , 0.18159105],
       [0.9936218 , 0.67697202, 0.75762167]])

In [58]:
np.random.rand(2, 3)

array([[0.80502665, 0.76188876, 0.14200583],
       [0.56108082, 0.33650395, 0.02111401]])

In [59]:
np.random.seed(2019)
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [60]:
np.random.randn(3, 2)

array([[ 0.57376143,  0.28772767],
       [-0.23563426,  0.95349024],
       [-1.6896253 , -0.34494271]])

In [61]:
np.random.normal(2, 1, size=3)

array([2.0169049 , 1.48501648, 2.24450929])

In [62]:
np.random.uniform(5, 10, size=3)

array([7.5680996 , 7.89150793, 6.49641327])

Почему вообще используют `numpy`?

In [65]:
n = 5
A = np.random.rand(n, n)
B = np.random.rand(n, n)
print(A, B)

[[0.8371974  0.52664983 0.10484424 0.27812941 0.04659494]
 [0.50907615 0.47242629 0.90448733 0.94349222 0.70339235]
 [0.84629795 0.92799464 0.81936188 0.84518556 0.79145187]
 [0.17100016 0.28997792 0.30448392 0.1476601  0.57381853]
 [0.86355701 0.32329947 0.27564943 0.68218738 0.19140631]] [[0.58102448 0.86255827 0.23452664 0.28985187 0.38285364]
 [0.34960393 0.32879374 0.94017484 0.0380261  0.77684511]
 [0.38464466 0.71672375 0.45246511 0.69896235 0.35362047]
 [0.79423435 0.29711244 0.25063809 0.85179036 0.81562092]
 [0.43428899 0.76359571 0.32958304 0.21278897 0.42188698]]


In [66]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

CPU times: user 134 µs, sys: 19 µs, total: 153 µs
Wall time: 159 µs


In [67]:
%%time
C = A @ B

CPU times: user 2.32 ms, sys: 31 µs, total: 2.35 ms
Wall time: 13.6 ms


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [68]:
#1
a = np.array([1,2,3,4,5])
a = np.flip(a)
print(a)


[5 4 3 2 1]


In [69]:
#2
a = np.random.randint(1, 10, size = 5)
print(a)
print(np.max(a[a%2==0]))



[5 4 1 9 7]
4


In [5]:
#3
a = np.random.randint(1, 10, size = 5)
print(a)
a[a%2!=0] = 7
print(a)

[2 4 3 3 3]
[2 4 7 7 7]


In [6]:
#4
n = 10
a = np.arange(2*n - 1, 0, -2)
print(a)

[19 17 15 13 11  9  7  5  3  1]


In [12]:
#5
from random import randint
a = np.random.randint(1, 10, size = 5)
b = randint(1, 10)
print(a)
print(b)
nearest = a[np.abs(a - b).argmin()]
farthest = a[np.abs(a - b).argmax()]
print(nearest, farthest)



[4 5 9 8 3]
10
9 3


In [83]:
#6
coeffs = np.array([4, 6, 0, 1])
n = len(coeffs)
primitive_coeffs = [coeffs[i] / (n - i) for i in range(n)]
primitive_coeffs.append(7)
print(np.array(primitive_coeffs))




[1. 2. 0. 1. 7.]


In [ ]:
# ┌(▼▼メ)┘ └(メ▼▼)┐