# Семинар 1: знакомство с NumPy


In [58]:
print('hi')

hi


## Немного про Jupyter notebook

Полная документация: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

---
В Jupyter Notebook есть два режима работы: режим _команд_ и режим _редактирования_

_Командный_ режим нужен для того, чтобы взаимодействовать и управлять ячейками (добавлять, удалять, запускать, копировать, ...)

В режиме _редактирования_ вы меняете содержимое ячейки.

Ячейки бывают двух основных типов, _код_ и _разметка_

### Полезные команды

(находясь в командном режиме)

- `a` - добавить пустую ячейку сверху

- `b` - добавить пустую ячейку снизу
- `c` - скопировать текущую ячейку
- `v` - вставить скопированную ячейку
- `d` - удалить текущую ячейку
- `x` - вырезать (удалить и скопировать) текущую ячейку
- `m` - изменить тип выбранной ячейки на "разметка"
- `y` - изменить тип выбранной ячейки на "код"
- `z` - отменить последнее действие


- `Enter` - начать редактировать выбранную ячейку

(будучи в режим редактирования ячейки)
- `esc` - вернуться в командный режим

(будучи в любом режиме)

- `Ctrl + Enter` - запустить выбранную ячейку
- `Shift + Enter` - запустить выбранную ячейку и выбрать следующую

In [ ]:
2 + 2

5

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [ ]:
import numpy as np

In [ ]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
vec

In [ ]:
print(vec)

С чем мы работаем?

In [ ]:
vec.dtype

In [ ]:
type(vec)

Размер массива:

In [ ]:
vec.shape

Число осей:

In [ ]:
vec.ndim

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [ ]:
np.sum(vec)

In [95]:
np.sum(vec, axis=0)

array([ 9, 12])

In [ ]:
np.sum(vec, axis=1)

In [ ]:
vec.sum()

Транспонируем массив:

In [ ]:
vec.T

In [ ]:
vec.transpose()

Обратите внимание, что переменная `vec` не поменялась!

In [ ]:
vec

Размеры массивов можно менять:

In [ ]:
vec.reshape(2, 3)

In [ ]:
vec.reshape(-1, 3)

In [ ]:
vec.reshape(2, -1)

Индексирование:

In [61]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
vec[:, 1]

array([2, 4, 6])

In [60]:
vec[2, :]

array([5, 6])

In [63]:
vec[1:2, 0]

array([3])

In [64]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

И, наконец - арифметические операции!

In [ ]:
vec + 1

In [ ]:
vec * 2

In [ ]:
vec**2

In [ ]:
vec + vec**2

In [ ]:
vec * vec**2

In [ ]:
np.sin(vec)

Матричное умножение:

In [ ]:
vec.dot(vec**2)

In [ ]:
vec.dot((vec**2).T)

In [ ]:
vec @ (vec**2).T

In [71]:
vec @ (vec.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [75]:
arr = np.arange(5, 10)*2
print(arr)

[10 12 14 16 18]


Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [65]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [67]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Булевы массивы:

In [ ]:
is_even = vec % 2 == 0
print(is_even)

In [ ]:
np.sum(is_even)

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [ ]:
vec[vec % 2 == 0]

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [ ]:
np.zeros((2, 3))

Массив из единиц:

In [ ]:
np.ones((3, 2))

Единичная матрица:

In [68]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [69]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [70]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [ ]:
np.vstack((vec, np.zeros(vec.shape)))

Генерация случайных чисел:

In [84]:
np.random.seed(623)
np.random.rand(2, 3)

array([[0.70373071, 0.8009102 , 0.18159105],
       [0.9936218 , 0.67697202, 0.75762167]])

In [ ]:
np.random.rand(2, 3)

In [ ]:
np.random.seed(2019)
np.random.rand(2, 3)

In [ ]:
np.random.randn(3, 2)

In [ ]:
np.random.normal(2, 1, size=3)

In [86]:
np.random.uniform(5, 10, size=3)

array([9.32723928, 5.41625783, 5.2441775 ])

Почему вообще используют `numpy`?

In [91]:
n = 5
A = np.random.rand(n, n)
B = np.random.rand(n, n)
print(A, B)

[[0.32191024 0.29570697 0.59032985 0.13882837 0.03106017]
 [0.47728784 0.01381855 0.81843669 0.76574703 0.81592872]
 [0.15656509 0.25384705 0.56272279 0.7108087  0.67811457]
 [0.99735906 0.83140903 0.54722494 0.22536127 0.33626338]
 [0.44015482 0.80799512 0.74498166 0.00474042 0.55648463]] [[0.83801111 0.66371322 0.28039527 0.05656517 0.72768947]
 [0.46719948 0.35920245 0.10489196 0.57660796 0.30388827]
 [0.33887665 0.75778126 0.13841428 0.62422804 0.95422868]
 [0.52102607 0.6336444  0.2102092  0.48300398 0.85455245]
 [0.36369087 0.48815341 0.11467766 0.8935834  0.54160192]]


In [88]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

KeyboardInterrupt: 

In [92]:
%%time
C = A @ B

CPU times: user 1.24 ms, sys: 0 ns, total: 1.24 ms
Wall time: 14.2 ms


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [98]:
#1
a = np.array([1,2,3,4,5])
a = np.flip(a)
print(a)


[5 4 3 2 1]


In [107]:
#2
a = np.random.randint(1, 10, size = 5)
print(a)
print(np.max(a[a%2==0]))



[5 4 3 9 6]
6


In [108]:
#3
a = np.random.randint(1, 10, size = 5)
print(a)
a[a%2!=0] = 7
print(a)

[5 2 7 4 6]
[7 2 7 4 6]


In [ ]:
# ┌(▼▼メ)┘ └(メ▼▼)┐